# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [3]:
x=1
y=3

def sum(a,b):
    return a+b
sum(x,y)

4

# 3.Define a list and replicate in three different ways.

In [4]:
items=["I","Love","Coding","and","want","to","learn","Python","!"]

#Method one:
print(items[:])
print(items)

#Method two:
new_list = list(items)
print(new_list)

#Method three:
import copy
the_newest_list = copy.copy(items)# copy
print(the_newest_list)

['I', 'Love', 'Coding', 'and', 'want', 'to', 'learn', 'Python', '!']
['I', 'Love', 'Coding', 'and', 'want', 'to', 'learn', 'Python', '!']
['I', 'Love', 'Coding', 'and', 'want', 'to', 'learn', 'Python', '!']
['I', 'Love', 'Coding', 'and', 'want', 'to', 'learn', 'Python', '!']


# 4.Define two lists and merge them together.

In [5]:
listone = ["I","Love","Coding"]
listtwo = ["and","want","to","learn","Python","!"]
print(listone)
print(listtwo)
listone.extend(listtwo)
print(listone)

['I', 'Love', 'Coding']
['and', 'want', 'to', 'learn', 'Python', '!']
['I', 'Love', 'Coding', 'and', 'want', 'to', 'learn', 'Python', '!']


# 5. Get the last element of the list and print it.

In [7]:
items=["I","Love","Coding","and","want","to","learn","Python","!"]
items[len(items)-1]

'!'

# 6.Define a tuple that contains only one element.

In [10]:
t=(1,)
print(t)
type(t)

(1,)


tuple

# 7.Define a three-line long string.

In [11]:
print('''
"this is a long string",\n he said. \n nice
''')


"this is a long string" 
 ,he said. 
 nice



# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [15]:
t=(1,2,"coding")
i=0
for i in t[0:len(t)]:
    print(i)

1
2
coding


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [17]:
x=8
y=6

def Mul(a,b):
    return a*b
Mul(x,y)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [18]:
import math 
import numpy as np

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [19]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [23]:
x=np.zeros((15,))
x = x.reshape(3,5)
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [24]:
A = np.arange(6).reshape(3,2)
B = np.arange(6).reshape(2,3)

In [25]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [26]:
B

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
np.matmul(A,B)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])